language: java
jdk: openjdk8
install: true
script:
- "mvn clean install -DskipTests -Darguments=\"-Dmaven.javadoc.skip=true\""
cache:
  directories:
  - "$HOME/.m2"

deploy:
  provider: "releases"
  skip_cleanup: true
  api_key:
    secure: "fscXl5+Lmf18qGyyiWNe25leJ0XFcM1uQaETNuGiroytRIi3rdSzrjJMEYGvnOnB7rqfetWEeecXFFiZlx2TD0Ly6+v1bfNdNGi+qo/JS8ZsxmdDIDB9j/JlvN4LiixBRSOb0O4FVKS0B44R+xGO6DXb6bwHwxWyrpCFLLRlaNouQSgqBwl9YnFoMCaAmbdtaO8NqmkEgAF0YYpBVUabiBbLQbEzEousAI13yog3sBdnQzX6S6wEbeDZYl0zPEg4UqCp6tK1zzplBcMsxAlFzswF/JXDj8wKJ3RXdHUu0t0wEl3xzkRWTUjPQmiVUJmSet8RrwXepkB6fDrdY1AsBFM2R/EedFsuR0WtnjWjlIgiSssaH3OqdIRoRdB7/DMZr6LiztOXxFsTBuzg5s4QvWYpUOwmXbxNjBdh2SDYO37oiccXbY6x+CSGQAwhdWf/4crg95osTPADJlmaRelZcRfHLnTRX16z+FN1isP2CQ26WoyaUJQx4Iqm3kIJkCsSPJXDRlqlv/1jgCARYc1LzsyeVUlWGfs2KlnfTMmxd0NMn1el7+tV/yhXBe4l598aTEalZJzQkVdAtt26HodG8zg1X635S8DKGMG+upll8pBCM6/w6znq2FyO5alLS15OuVDBSEz+qwPL1OWS7U6umKOOG4w1Q1nVrbOzXcy/8E8="
  file: "*/*.jar"
  file_glob: true
  on:
    repo: "stelar7/R4J"
    tags: true

notifications:
  email: false

after_success:
  on:
    tags: true
